# Generated by Django 3.0.7 on 2020-06-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='qs_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
